config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :lists
  devise_for :users
  root to: "lists#index"

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # require auth on everything
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :deadline, :finished_at, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # helper to make bootstrap3 nav-pill <li>'s with links in them, that have
  # proper 'active' class if active.
  #
  # the current pill will have 'active' tag on the <li>
  #
  # html_options param will apply to <li>, not <a>.
  #
  # can pass block which will be given to `link_to` as normal.
  def nav_to(label, link_params, html_options = {})
    current = current_page?(link_params)

    if current
      html_options[:class] ||= ""
      html_options[:class] << " active "
    end

    content_tag(:li, html_options) do
      link_to(label, link_params)
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<div class="container navbar-fixed-bottom">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <p class="navbar-text">By <%= link_to "Michal Papis", "https://github.com/mpapis" %></p>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/_menu.html.erb
<div class="container navbar-fixed-top">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%= nav_to "Home", root_path %>
          <%= nav_to "Lists", lists_path %>
          <%= nav_to "Tasks", tasks_path %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? then %>
            <%= nav_to "Logout",  destroy_user_session_path %>
          <% else %>
            <%= nav_to "Login",   new_user_session_path %>
            <%= nav_to "Sign up", new_user_registration_path %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/menu" %>
    <div class=container>
      <%- if notice then %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <%- if alert then %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :finished_at %><br>
    <%= f.datetime_select :finished_at %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br>
    <%= f.text_field :list_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Deadline</th>
      <th>Finished at</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.deadline %></td>
        <td><%= task.finished_at %></td>
        <td><%= task.list %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @task.finished_at %>
</p>

<p>
  <strong>List:</strong>
  <%= @task.list %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>